In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
annot = pd.read_csv('./annotations/annotations_merged.csv')
annot.head(10)

,UserID,PromptID,PMCID,Valid Label,Valid Reasoning,Label,Annotations,Label Code,In Abstract,Evidence Start,Evidence End
0,0,213,2206488,True,True,no significant difference,IL-6r (ng/ml)\t\t\t\t\t\t\t Group A\t43.6 (1.7...,0,False,-1,-1
1,1,213,2206488,True,True,no significant difference,"There was no significant difference in IL 6, I...",0,True,1612,1708
2,3,213,2206488,True,True,no significant difference,"There was no significant difference in IL 6, I...",0,True,1612,1707
3,2,213,2206488,True,True,no significant difference,"There was no significant difference in IL 6, I...",0,True,1612,1707
4,0,98,2858204,True,True,significantly increased,"After two weeks of treatment, the reduction in...",1,True,18239,18338
5,1,98,2858204,True,True,significantly increased,"After two weeks of treatment, the reduction in...",1,True,18239,18339
6,3,98,2858204,True,True,significantly increased,"After two weeks of treatment, the reduction in...",1,True,18239,18339
7,2,98,2858204,True,True,significantly increased,"After two weeks of treatment, the reduction in...",1,True,18239,18339
8,0,150,2871176,True,True,significantly increased,The proportion of subjects experiencing minor ...,1,False,25524,26184
9,3,150,2871176,True,True,significantly increased,Incidence was higher with liraglutide 1.2 mg (...,1,False,25964,26073

In [16]:
annot.sort_values('PMCID').head(10)

,UserID,PromptID,PMCID,Valid Label,Valid Reasoning,Label,Annotations,Label Code,In Abstract,Evidence Start,Evidence End
13994,0,7902,60007,True,True,significantly increased,Mivacurium 250 μg/kg produced a maximal T bloc...,1,True,1280,1395
14000,3,7904,60007,True,True,no significant difference,Heart rate was similar between doses,0,True,1452,1488
12483,0,7905,60007,True,True,significantly decreased,while both AUC-SBP and AUC-DBP were significan...,-1,False,16737,16836
12484,1,7905,60007,True,True,significantly decreased,"In relation to the cardiovascular response, th...",-1,False,16641,16836
13999,0,7904,60007,True,True,no significant difference,"In relation to the cardiovascular response, th...",0,False,16641,16736
13998,3,7903,60007,True,True,no significant difference,Spontaneous recovery times were similar in bot...,0,True,1396,1450
13997,0,7903,60007,True,True,no significant difference,The times to OA and to spontaneous recovery of...,0,False,14755,15079
13995,3,7902,60007,True,True,significantly increased,Mivacurium 250 μg/kg produced a maximal T bloc...,1,True,1280,1395
2855,0,1806,111193,True,True,no significant difference,The amount of blood transfusion was identical ...,0,True,1418,1578
2334,0,1808,111193,True,True,no significant difference,There was no difference in time spent in hospi...,0,False,14701,14770

In [3]:
 for i in range(10):
    print(i, annot['Annotations'][i])

0 IL-6r (ng/ml)							 Group A	43.6 (1.7–125.0)		47.4 (0.7–109.5)	56.2 (25.2–226.3)			0.949† Group B	40.7 (15.6–94.6)		42.4 (22.2–100.5)	50.2 (13.2–104.9)			0.861†	p = 0.607*		p = 0.914*	p = 0.304*
1 There was no significant difference in IL 6, IL-6r and C-reactive protein values between groups.
2 There was no significant difference in IL 6, IL-6r and C-reactive protein values between groups
3 There was no significant difference in IL 6, IL-6r and C-reactive protein values between groups
4 After two weeks of treatment, the reduction in ulcer area was doubled in the HBOT group (P = 0.037)
5 After two weeks of treatment, the reduction in ulcer area was doubled in the HBOT group (P = 0.037).
6 After two weeks of treatment, the reduction in ulcer area was doubled in the HBOT group (P = 0.037).
7 After two weeks of treatment, the reduction in ulcer area was doubled in the HBOT group (P = 0.037).
8 The proportion of subjects experiencing minor hypoglycaemia during the trial was lowest with placebo (i.e. glimepiride monotherapy 2.6%; 0.17 events/subject-year), comparable with liraglutide 0.6 mg (5.2%, 0.17 events/subject-year) and rosiglitazone (4.3%, 0.12 events/subject-year) groups and similar between the liraglutide 1.2 mg (9.2%, 0.51 events/subject-year) and liraglutide 1.8 mg (8.1%, 0.47 events/subject-year) treatment groups. Incidence was higher with liraglutide 1.2 mg (P = 0.0024) and 1.8 mg (P = 0.0065) compared with rosiglitazone and liraglutide 1.2 mg compared with placebo (P = 0.048), occurring in the setting of lower mean HbA1c values.
9 Incidence was higher with liraglutide 1.2 mg (P = 0.0024) and 1.8 mg (P = 0.0065) compared with rosiglitazone

In [5]:
print("Annotations len: ", len(annot))
print("Unique PMCID: ", len(annot['PMCID'].unique()))
print("Unique PromptID numbers: ", len(annot['PromptID'].unique()))

Annotations len:  19716
Unique PMCID:  2417
Unique PromptID numbers:  10113

In [6]:
prompt = pd.read_csv('./annotations/prompts_merged.csv')

In [15]:
prompt.sort_values('PMCID').head(10)

,PromptID,PMCID,Outcome,Intervention,Comparator
7217,7902,60007,maximal T block,mivacurium 250 μg/kg,mivacurium 200 μg/kg
6459,7905,60007,systolic blood pressure (SBP) and diastolic bl...,mivacurium 250 μg/kg,mivacurium 200 μg/kg
7219,7903,60007,Spontaneous recovery time,mivacurium 250 μg/kg,mivacurium 200 μg/kg
7220,7904,60007,heart rate (HR),mivacurium 250 μg/kg,mivacurium 200 μg/kg
1458,1804,111193,"Blood loss, excluding intraoperative blood loss",Preoperative acute normovolaemic hemodilution ...,No preoperative hemodilution (non-ANH)
1459,1806,111193,Amount of transfused blood,Preoperative acute normovolaemic hemodilution ...,No preoperative hemodilution (non-ANH)
1308,1807,111193,Mean artery blood pressure during surgery,Preoperative acute normovolaemic hemodilution ...,No preoperative hemodilution (non-ANH)
1193,1808,111193,Hospital stay,Preoperative acute normovolaemic hemodilution ...,No preoperative hemodilution (non-ANH)
1192,1805,111193,Surgery duration,Preoperative acute normovolaemic hemodilution ...,No preoperative hemodilution (non-ANH)
467,550,125315,The 28-day mortality,received standard therapy for sepsis and physi...,received only standard therapy for sepsis

In [8]:
prompt.dtypes

PromptID         int64
PMCID            int64
Outcome         object
Intervention    object
Comparator      object
dtype: object

In [10]:
print("Prompt numbers: ", len(prompt))
print("Unique PMCID: ", len(prompt['PMCID'].unique()))
print("Unique PromptID numbers: ", len(prompt['PromptID'].unique()))

Prompt numbers:  10137
Unique PMCID:  2419
Unique PromptID numbers:  10137